"""
webapp.py
=========
A simple Streamlit web interface around excel_automation.run_pipeline(),
so the weekly report can be generated by anyone on the team from a link --
no Python, no folders, no command line.

Flow for a team member:
    1. Open the link.
    2. Upload the main network export zip (required).
    3. Upload the Cell DB Export and/or power license export (optional --
       skip either one if you don't have it this week; those columns are
       just left blank).
    4. Click "Generate report", download it immediately.

Every generated report also gets committed to this same GitHub repo, under
reports/<date>.xlsx -- ONE file per day, overwritten (same commit path) if
the report is regenerated the same day. The "Previous Reports" tab lists
everything under reports/ with a download button. This survives app
restarts/redeploys (it's stored in git, not the app's own disk).

NOTE: this means each day's generated report -- containing real network
data (NE IDs, site names, traffic, power values) -- becomes part of this
repo's git history going forward. Keep the repo private. This was a
deliberate tradeoff after other free storage options (Cloudflare R2,
Supabase, Firebase Storage) all required a billing card just to use their
storage product.

REQUIRED SETUP (one-time, done by whoever administers this app)
    1. Create a GitHub Personal Access Token (fine-grained, scoped to just
       this repo, "Contents: Read and write" permission) for whichever
       account owns this repo.
    2. In the Streamlit Cloud app's Settings -> Secrets, add:

        [github]
        token = "github_pat_..."

    Without this configured, report generation and direct download still
    work -- only the "Previous Reports" history is unavailable.

The report template (template/basic_configurations.xlsx) is bundled with
this app -- nobody uploads it, it's the same one every week.

RUN LOCALLY
    pip install -r requirements.txt
    streamlit run webapp.py

DEPLOY (free)
    Push this repo to GitHub, then deploy it on Streamlit Community Cloud
    (share.streamlit.io) pointing at webapp.py. You get a shareable
    https://<name>.streamlit.app link.
"""

import base64
import contextlib
import io
import os
import tempfile
from datetime import datetime

import requests
import streamlit as st

import excel_automation as ea

st.set_page_config(page_title="Weekly Cell Config Report", page_icon="\U0001F4F6", layout="centered")

GITHUB_REPO = "Pathirana-Pavani/cell-config-weekly-report"
GITHUB_BRANCH = "main"
GITHUB_REPORTS_DIR = "reports"
GITHUB_API = "https://api.github.com"


# ---------------------------------------------------------------------------
# GitHub-as-storage -- one committed file per day, overwritten same-day.
# ---------------------------------------------------------------------------

def github_token():
    return st.secrets.get("github", {}).get("token")


def github_headers():
    return {
        "Authorization": f"Bearer {github_token()}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def upload_daily_report(output_bytes, source_filename):
    """
    Commit today's report to reports/<date>.xlsx in this repo. If that
    path already has a commit from earlier today, this overwrites it
    (same path, new commit) -- one file per day, regardless of what the
    source zip was named.
    """
    token = github_token()
    if not token:
        return None, "GitHub storage isn't configured -- report was not saved to persistent storage."

    today = datetime.now().strftime("%Y-%m-%d")
    path = f"{GITHUB_REPORTS_DIR}/{today}.xlsx"
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/{path}"

    # Look up the current file's sha (required by the API to overwrite an
    # existing file); absent if this is the first report of the day.
    existing_sha = None
    r = requests.get(url, headers=github_headers(), params={"ref": GITHUB_BRANCH})
    if r.status_code == 200:
        existing_sha = r.json()["sha"]
    elif r.status_code != 404:
        return None, f"Could not check existing report: {r.status_code} {r.text[:200]}"

    body = {
        "message": f"Daily report {today} ({source_filename})",
        "content": base64.b64encode(output_bytes).decode("ascii"),
        "branch": GITHUB_BRANCH,
    }
    if existing_sha:
        body["sha"] = existing_sha

    r = requests.put(url, headers=github_headers(), json=body)
    if r.status_code in (200, 201):
        return path, None
    return None, f"Could not save to persistent storage: {r.status_code} {r.text[:200]}"


def list_daily_reports():
    """Newest-first list of dicts (day, sha, size, name). None if not configured, [] if empty."""
    if not github_token():
        return None
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/{GITHUB_REPORTS_DIR}"
    r = requests.get(url, headers=github_headers(), params={"ref": GITHUB_BRANCH})
    if r.status_code == 404:
        return []
    r.raise_for_status()

    items = []
    for entry in r.json():
        if not entry["name"].endswith(".xlsx"):
            continue
        day = entry["name"][:-len(".xlsx")]
        items.append({"day": day, "sha": entry["sha"], "size": entry["size"], "name": entry["name"]})
    items.sort(key=lambda x: x["day"], reverse=True)
    return items


def fetch_report_bytes(sha):
    """Fetch a file's raw bytes by blob sha (works past the Contents API's
    1MB inline-content limit, unlike GET-ing the file path directly)."""
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/git/blobs/{sha}"
    r = requests.get(url, headers=github_headers())
    r.raise_for_status()
    return base64.b64decode(r.json()["content"])


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------

st.title("Weekly Cell Config Report")

tab_generate, tab_history = st.tabs(["Generate Report", "Previous Reports"])

with tab_generate:
    st.caption(
        "Upload this week's network export (and, optionally, the Cell DB export "
        "and power license export) to generate the filled report."
    )

    with st.form("report_form"):
        zip_file = st.file_uploader(
            "Main network export (.zip)",
            type=["zip"],
            help="The weekly zipped radio-config export containing the EUtranCellFDD workbook.",
        )
        cell_db_file = st.file_uploader(
            "Cell DB Export (optional)",
            type=["xlsx", "xlsm"],
            help="Fills the 'Traffic @ <date>' column. Skip this if you don't have it -- "
                 "that column is just left as-is.",
        )
        power_license_file = st.file_uploader(
            "Power license export (optional)",
            type=["xlsx", "xlsm"],
            help="Fills 'FDD Power (W)Authorization Value' and 'LTE FDD(W) Configuration "
                 "Value'. Skip this if you don't have it -- those columns are left blank.",
        )
        submitted = st.form_submit_button("Generate report", type="primary")

    if submitted:
        if zip_file is None:
            st.error("Please upload the main network export zip file.")
            st.stop()

        template_path = ea.find_template_file(ea.TEMPLATE_DIR)
        if not template_path:
            st.error(
                "No template file found in this app's template/ folder. "
                "This is a setup problem, not something you can fix here -- "
                "contact whoever maintains this app."
            )
            st.stop()

        with tempfile.TemporaryDirectory(prefix="report_run_") as work_dir:
            zip_path = os.path.join(work_dir, zip_file.name)
            with open(zip_path, "wb") as f:
                f.write(zip_file.getbuffer())

            other_exports_dir = os.path.join(work_dir, "other_exports")
            os.makedirs(other_exports_dir, exist_ok=True)

            cell_db_path = None
            if cell_db_file is not None:
                cell_db_path = os.path.join(other_exports_dir, cell_db_file.name)
                with open(cell_db_path, "wb") as f:
                    f.write(cell_db_file.getbuffer())

            power_license_path = None
            if power_license_file is not None:
                power_license_path = os.path.join(other_exports_dir, power_license_file.name)
                with open(power_license_path, "wb") as f:
                    f.write(power_license_file.getbuffer())

            output_dir = os.path.join(work_dir, "output")

            log_buffer = io.StringIO()
            try:
                with st.spinner("Processing... this can take a few minutes for large exports."):
                    with contextlib.redirect_stdout(log_buffer):
                        output_path, summary = ea.run_pipeline(
                            zip_path, template_path, other_exports_dir, output_dir,
                            cell_db_export_path=cell_db_path,
                            power_license_path=power_license_path,
                        )
            except ea.AutomationError as e:
                st.error(f"Could not generate the report: {e}")
                with st.expander("Full processing log"):
                    st.text(log_buffer.getvalue())
                st.stop()
            except Exception as e:  # unexpected -- still show the log to help debugging
                st.error(f"Unexpected error: {e}")
                with st.expander("Full processing log"):
                    st.text(log_buffer.getvalue())
                st.stop()

            with open(output_path, "rb") as f:
                output_bytes = f.read()

        st.success(f"Report generated: {summary['rows_read']} cell rows written.")

        st.download_button(
            "Download filled report",
            data=output_bytes,
            file_name=summary["output_name"],
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            type="primary",
        )

        saved_key, save_error = upload_daily_report(output_bytes, summary["source_filename"])
        if save_error:
            st.warning(save_error)
        else:
            st.caption(f"Also saved to persistent storage as today's report ({saved_key.rsplit('/', 1)[-1]}).")

        st.subheader("Summary")
        col1, col2, col3 = st.columns(3)
        col1.metric("Rows written", summary["rows_read"])
        col2.metric("RS power matched", f"{summary['rs_power']['entries'] - summary['rs_power']['misses']}"
                                         f"/{summary['rows_read']}")
        col3.metric("P_A_DTCH matched", f"{summary['rows_read'] - summary['pa_dtch']['misses']}"
                                         f"/{summary['rows_read']}")

        col4, col5, col6 = st.columns(3)
        col4.metric("CellMeasGroup matched", f"{summary['rows_read'] - summary['cell_meas_group']['misses']}"
                                              f"/{summary['rows_read']}")
        if summary["traffic"]:
            col5.metric(f"Traffic matched ({summary['traffic']['label']})",
                        f"{summary['rows_read'] - summary['traffic']['misses']}/{summary['rows_read']}")
        else:
            col5.metric("Traffic matched", "not provided")
        if summary["power_license"]:
            col6.metric("Power license matched",
                        f"{summary['rows_read'] - summary['power_license']['misses']}/{summary['rows_read']}")
        else:
            col6.metric("Power license matched", "not provided")

        if summary["warnings"]:
            with st.expander(f"Warnings ({len(summary['warnings'])})", expanded=False):
                for w in summary["warnings"]:
                    st.warning(w)

        with st.expander("Full processing log"):
            st.text(log_buffer.getvalue())

with tab_history:
    st.caption(
        "One report per day -- regenerating later the same day replaces that day's file. "
        "Stored as commits in this app's GitHub repo, so this survives app restarts/redeploys."
    )

    items = list_daily_reports()
    if items is None:
        st.info(
            "Persistent storage isn't configured yet. Add the `[github]` secrets block "
            "in this app's Settings -> Secrets to enable this tab."
        )
    elif not items:
        st.caption("No reports saved yet.")
    else:
        for item in items:
            col_day, col_name, col_dl = st.columns([1.3, 3, 1.3])
            col_day.write(item["day"])
            col_name.write(item["name"])
            col_dl.download_button(
                "Download",
                data=fetch_report_bytes(item["sha"]),
                file_name=item["name"],
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                key=f"dl_{item['day']}",
            )
