"""
webapp.py
=========
A simple Streamlit web interface around excel_automation.run_pipeline(),
so the weekly report can be generated by anyone on the team from a link --
no Python, no folders, no command line.

Flow for a team member:
    1. Open the link.
    2. Upload the main network export zip (required).
    3. Upload the Cell DB Export and/or power license export (optional --
       skip either one if you don't have it this week; those columns are
       just left blank).
    4. Click "Generate report", download it immediately.

Every generated report also gets committed to this same GitHub repo, under
reports/<date>.xlsx -- ONE file per day, overwritten (same commit path) if
the report is regenerated the same day. The "Previous Reports" tab lists
everything under reports/ with a download button. This survives app
restarts/redeploys (it's stored in git, not the app's own disk).

NOTE: this means each day's generated report -- containing real network
data (NE IDs, site names, traffic, power values) -- becomes part of this
repo's git history going forward. Keep the repo private. This was a
deliberate tradeoff after other free storage options (Cloudflare R2,
Supabase, Firebase Storage) all required a billing card just to use their
storage product.

REQUIRED SETUP (one-time, done by whoever administers this app)
    1. Create a GitHub Personal Access Token (fine-grained, scoped to just
       this repo, "Contents: Read and write" permission) for whichever
       account owns this repo.
    2. In the Streamlit Cloud app's Settings -> Secrets, add:

        [github]
        token = "github_pat_..."

    Without this configured, report generation and direct download still
    work -- only the "Previous Reports" history is unavailable.

The report template (template/basic_configurations.xlsx) is bundled with
this app -- nobody uploads it, it's the same one every week.

RUN LOCALLY
    pip install -r requirements.txt
    streamlit run webapp.py

DEPLOY (free)
    Push this repo to GitHub, then deploy it on Streamlit Community Cloud
    (share.streamlit.io) pointing at webapp.py. You get a shareable
    https://<name>.streamlit.app link.
"""

import base64
import contextlib
import io
import os
import tempfile
import time
from datetime import datetime

import pandas as pd
import requests
import streamlit as st

import excel_automation as ea

st.set_page_config(page_title="Weekly Cell Config Report", page_icon="\U0001F4F6", layout="centered")

GITHUB_REPO = "Pathirana-Pavani/cell-config-weekly-report"
GITHUB_BRANCH = "main"
GITHUB_REPORTS_DIR = "reports"
GITHUB_API = "https://api.github.com"


# ---------------------------------------------------------------------------
# GitHub-as-storage -- one committed file per day, overwritten same-day.
# ---------------------------------------------------------------------------

def github_token():
    return st.secrets.get("github", {}).get("token")


def github_headers():
    return {
        "Authorization": f"Bearer {github_token()}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def upload_daily_report(output_bytes, source_filename):
    """
    Commit today's report to reports/<date>.xlsx in this repo. If that
    path already has a commit from earlier today, this overwrites it
    (same path, new commit) -- one file per day, regardless of what the
    source zip was named.
    """
    token = github_token()
    if not token:
        return None, "GitHub storage isn't configured -- report was not saved to persistent storage."

    today = datetime.now().strftime("%Y-%m-%d")
    path = f"{GITHUB_REPORTS_DIR}/{today}.xlsx"
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/{path}"

    # Look up the current file's sha (required by the API to overwrite an
    # existing file); absent if this is the first report of the day.
    existing_sha = None
    r = requests.get(url, headers=github_headers(), params={"ref": GITHUB_BRANCH})
    if r.status_code == 200:
        existing_sha = r.json()["sha"]
    elif r.status_code != 404:
        return None, f"Could not check existing report: {r.status_code} {r.text[:200]}"

    body = {
        "message": f"Daily report {today} ({source_filename})",
        "content": base64.b64encode(output_bytes).decode("ascii"),
        "branch": GITHUB_BRANCH,
    }
    if existing_sha:
        body["sha"] = existing_sha

    r = requests.put(url, headers=github_headers(), json=body)
    if r.status_code in (200, 201):
        return path, None
    return None, f"Could not save to persistent storage: {r.status_code} {r.text[:200]}"


@st.cache_data(ttl=60, show_spinner=False)
def list_daily_reports():
    """
    Newest-first list of dicts (day, sha, size, name). None if not configured, [] if empty.
    Cached for 60s -- without this, typing in the search box below (which
    reruns the whole script on every keystroke) would re-fetch this list
    from GitHub's API on every single character, which is slow and
    especially painful for remote sites on weak connections.
    """
    if not github_token():
        return None
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/{GITHUB_REPORTS_DIR}"
    r = requests.get(url, headers=github_headers(), params={"ref": GITHUB_BRANCH})
    if r.status_code == 404:
        return []
    r.raise_for_status()

    items = []
    for entry in r.json():
        if not entry["name"].endswith(".xlsx"):
            continue
        day = entry["name"][:-len(".xlsx")]
        items.append({"day": day, "sha": entry["sha"], "size": entry["size"], "name": entry["name"]})
    items.sort(key=lambda x: x["day"], reverse=True)
    return items


def fetch_report_bytes(sha):
    """Fetch a file's raw bytes by blob sha (works past the Contents API's
    1MB inline-content limit, unlike GET-ing the file path directly)."""
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/git/blobs/{sha}"
    r = requests.get(url, headers=github_headers())
    r.raise_for_status()
    return base64.b64decode(r.json()["content"])


# ---------------------------------------------------------------------------
# In-app table view -- the saved .xlsx only stores FORMULA TEXT for the
# NEID_CellID/Site Name/Absolute sector/Absolute Sector/Name TAG columns
# (Excel computes the actual values on open; nothing has ever opened these
# generated files in real Excel to cache a result). Reading them straight
# into pandas would show blanks or raw "=B2&C2" text, so recompute those
# columns here in Python using the exact same logic as the formulas in
# excel_automation.py's FORMULA_COLUMNS.
# ---------------------------------------------------------------------------

def _excel_find(needle, haystack, start=1):
    idx = haystack.find(needle, start - 1)
    return None if idx == -1 else idx + 1


def _compute_site_name(user_label):
    if not isinstance(user_label, str):
        return user_label
    pos = _excel_find("_L", user_label)
    return user_label[:pos - 1] if pos else user_label


def _compute_absolute_sector(user_label):
    if not isinstance(user_label, str):
        return user_label
    p1 = _excel_find("L", user_label)
    p2 = _excel_find("_L", user_label)
    if not p1 or not p2:
        return user_label
    start = p2 + 2
    end = _excel_find("-", user_label, start)
    if not end:
        return user_label
    return user_label[:p1 - 1] + user_label[start - 1:end - 1]


def _remap_absolute_sector(last_char):
    """1/2/3 stay as-is, 4-8 shift down to 1-5, anything else -> blank."""
    if not isinstance(last_char, str) or not last_char.isdigit():
        return ""
    d = int(last_char)
    if 1 <= d <= 3:
        return str(d)
    if 4 <= d <= 8:
        return str(d - 3)
    return ""


def recompute_formula_columns(df):
    if "NE ID" in df.columns and "E-UTRAN FDD Cell ID" in df.columns and "NEID_CellID" in df.columns:
        df["NEID_CellID"] = df["NE ID"].astype(str) + df["E-UTRAN FDD Cell ID"].astype(str)
    if "User Label" in df.columns:
        if "Site Name" in df.columns:
            df["Site Name"] = df["User Label"].map(_compute_site_name)
        if "Absolute sector" in df.columns:
            df["Absolute sector"] = df["User Label"].map(_compute_absolute_sector)
        if "Name TAG" in df.columns:
            df["Name TAG"] = df["User Label"].astype(str).str[-3:]
    if "Absolute sector" in df.columns and "Absolute Sector" in df.columns:
        df["Absolute Sector"] = df["Absolute sector"].astype(str).str[-1:].map(_remap_absolute_sector)
    return df


@st.cache_data(show_spinner=False)  # spinner is shown inline where it's called instead (see below) --
def load_report_dataframe(sha):     # cache_data's own spinner renders as a small top-right overlay,
                                     # easy to miss right where the table is about to appear.
    """Returns (raw_bytes, dataframe) for a report blob, cached by sha
    (immutable, so this never needs to re-fetch/re-parse the same report)."""
    raw = fetch_report_bytes(sha)
    df = pd.read_excel(io.BytesIO(raw), sheet_name=0, dtype=str)
    df = recompute_formula_columns(df)
    return raw, df


# ---------------------------------------------------------------------------
# Live progress -- run_pipeline()'s row-reading step is the slow part
# (often 1-8+ minutes for large exports) and otherwise prints nothing
# until it's completely done, which looks like the app has frozen. This
# streams each log line to a placeholder as it happens, with an elapsed
# timer, while also buffering everything for the "Full processing log".
# ---------------------------------------------------------------------------

class LiveLogStream:
    def __init__(self, buffer, placeholder, start_time):
        self.buffer = buffer
        self.placeholder = placeholder
        self.start_time = start_time
        self._pending = ""

    def write(self, text):
        self.buffer.write(text)
        self._pending += text
        if "\n" in self._pending:
            *complete_lines, self._pending = self._pending.split("\n")
            last_line = next((line for line in reversed(complete_lines) if line.strip()), None)
            if last_line:
                elapsed = time.time() - self.start_time
                self.placeholder.text(f"[{elapsed:5.1f}s] {last_line.strip()}")

    def flush(self):
        pass


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------

st.title("Weekly Cell Config Report")

tab_generate, tab_history = st.tabs(["Generate Report", "Previous Reports"])

with tab_generate:
    tab_huawei, tab_zte = st.tabs(["Huawei Sites", "ZTE Sites"])

    with tab_huawei:
        st.caption(
            "Upload network export zip file and (optionally, the Cell DB export "
            "and power license export) to generate the filled report."
        )
    
        with st.form("report_form"):
            zip_file = st.file_uploader(
                "Main network export (.zip)",
                type=["zip"],
                help="The weekly zipped radio-config export containing the EUtranCellFDD workbook.",
            )
            cell_db_file = st.file_uploader(
                "Cell DB Export (optional)",
                type=["xlsx", "xlsm"],
                help="Fills the 'Traffic @ <date>' column. Skip this if you don't have it -- "
                     "that column is just left as-is.",
            )
            power_license_file = st.file_uploader(
                "Power license export (optional)",
                type=["xlsx", "xlsm"],
                help="Fills 'FDD Power (W)Authorization Value' and 'LTE FDD(W) Configuration "
                     "Value'. Skip this if you don't have it -- those columns are left blank.",
            )
            submitted = st.form_submit_button("Generate report", type="primary")
    
        if submitted:
            if zip_file is None:
                st.error("Please upload the main network export zip file.")
                st.stop()
    
            template_path = ea.find_template_file(ea.TEMPLATE_DIR)
            if not template_path:
                st.error(
                    "No template file found in this app's template/ folder. "
                    "This is a setup problem, not something you can fix here -- "
                    "contact whoever maintains this app."
                )
                st.stop()
    
            with tempfile.TemporaryDirectory(prefix="report_run_") as work_dir:
                zip_path = os.path.join(work_dir, zip_file.name)
                with open(zip_path, "wb") as f:
                    f.write(zip_file.getbuffer())
    
                other_exports_dir = os.path.join(work_dir, "other_exports")
                os.makedirs(other_exports_dir, exist_ok=True)
    
                cell_db_path = None
                if cell_db_file is not None:
                    cell_db_path = os.path.join(other_exports_dir, cell_db_file.name)
                    with open(cell_db_path, "wb") as f:
                        f.write(cell_db_file.getbuffer())
    
                power_license_path = None
                if power_license_file is not None:
                    power_license_path = os.path.join(other_exports_dir, power_license_file.name)
                    with open(power_license_path, "wb") as f:
                        f.write(power_license_file.getbuffer())
    
                output_dir = os.path.join(work_dir, "output")
    
                log_buffer = io.StringIO()
                start_time = time.time()
                try:
                    with st.status("Generating report...", expanded=True) as status_box:
                        status_line = st.empty()
                        live_stream = LiveLogStream(log_buffer, status_line, start_time)
                        with contextlib.redirect_stdout(live_stream):
                            output_path, summary = ea.run_pipeline(
                                zip_path, template_path, other_exports_dir, output_dir,
                                cell_db_export_path=cell_db_path,
                                power_license_path=power_license_path,
                            )
                        status_box.update(
                            label=f"Report generated in {time.time() - start_time:.1f}s",
                            state="complete",
                        )
                except ea.AutomationError as e:
                    status_box.update(label="Failed", state="error")
                    st.error(f"Could not generate the report: {e}")
                    with st.expander("Full processing log"):
                        st.text(log_buffer.getvalue())
                    st.stop()
                except Exception as e:  # unexpected -- still show the log to help debugging
                    status_box.update(label="Failed", state="error")
                    st.error(f"Unexpected error: {e}")
                    with st.expander("Full processing log"):
                        st.text(log_buffer.getvalue())
                    st.stop()
    
                with open(output_path, "rb") as f:
                    output_bytes = f.read()
    
            st.success(f"Report generated: {summary['rows_read']} cell rows written.")
    
            st.download_button(
                "Download filled report",
                data=output_bytes,
                file_name=summary["output_name"],
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                type="primary",
            )
    
            saved_key, save_error = upload_daily_report(output_bytes, summary["source_filename"])
            if save_error:
                st.warning(save_error)
            else:
                st.caption(f"Also saved to persistent storage as today's report ({saved_key.rsplit('/', 1)[-1]}).")
    
            st.subheader("Summary")
            col1, col2, col3 = st.columns(3)
            col1.metric("Rows written", summary["rows_read"])
            col2.metric("RS power matched", f"{summary['rs_power']['entries'] - summary['rs_power']['misses']}"
                                             f"/{summary['rows_read']}")
            col3.metric("P_A_DTCH matched", f"{summary['rows_read'] - summary['pa_dtch']['misses']}"
                                             f"/{summary['rows_read']}")
    
            col4, col5, col6 = st.columns(3)
            col4.metric("CellMeasGroup matched", f"{summary['rows_read'] - summary['cell_meas_group']['misses']}"
                                                  f"/{summary['rows_read']}")
            if summary["traffic"]:
                col5.metric(f"Traffic matched ({summary['traffic']['label']})",
                            f"{summary['rows_read'] - summary['traffic']['misses']}/{summary['rows_read']}")
            else:
                col5.metric("Traffic matched", "not provided")
            if summary["power_license"]:
                col6.metric("Power license matched",
                            f"{summary['rows_read'] - summary['power_license']['misses']}/{summary['rows_read']}")
            else:
                col6.metric("Power license matched", "not provided")
    
            if summary["warnings"]:
                with st.expander(f"Warnings ({len(summary['warnings'])})", expanded=False):
                    for w in summary["warnings"]:
                        st.warning(w)
    
            with st.expander("Full processing log"):
                st.text(log_buffer.getvalue())

    with tab_zte:
        st.caption("ZTE site report generation -- not yet implemented.")
        st.info(
            "This will use different processing logic than Huawei sites "
            "(different export format/sheets/columns). Waiting on the "
            "specifics before this is built out."
        )

with tab_history:
    st.caption(
        "One report per day -- regenerating later the same day replaces that day's file. "
        "Browse it right here, or download it below."
    )

    with st.spinner("Loading list of available reports..."):
        items = list_daily_reports()
    if items is None:
        st.info(
            "Persistent storage isn't configured yet. Add the `[github]` secrets block "
            "in this app's Settings -> Secrets to enable this tab."
        )
    elif not items:
        st.caption("No reports saved yet.")
    else:
        day_options = [item["day"] for item in items]  # already newest-first
        selected_day = st.selectbox("Report date", day_options, index=0)
        selected_item = next(item for item in items if item["day"] == selected_day)

        with st.spinner(f"Loading {selected_day} report..."):
            raw_bytes, df = load_report_dataframe(selected_item["sha"])

        # Search is inside a form so typing/deleting doesn't rerun (and
        # re-filter) on every keystroke -- only on Enter/Search click. This
        # matters a lot for remote sites on weak connections, where every
        # keystroke otherwise means a full round trip to the app.
        with st.form("search_form"):
            col_search, col_btn = st.columns([4, 1.3])
            search = col_search.text_input(
                "Search",
                placeholder="Type to filter rows across every column (NE ID, User Label, PCI, ...)",
                label_visibility="collapsed",
            )
            col_btn.form_submit_button("Search", type="primary", use_container_width=True)

        st.download_button(
            "Download .xlsx",
            data=raw_bytes,
            file_name=selected_item["name"],
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            key=f"dl_{selected_item['day']}",
        )

        display_df = df
        if search:
            mask = df.apply(lambda col: col.str.contains(search, case=False, na=False)).any(axis=1)
            display_df = df[mask]

        st.caption(f"Showing {len(display_df):,} of {len(df):,} rows")
        st.dataframe(display_df, use_container_width=True, height=500, hide_index=True)
